### ISSUE TITLE
--hide problem

### ISSUE THREAD

**Issue by xmulara** [rkorzen/KreaturaParser#2]
W przypadku napisania pytania w ten sposób:

Q S P4C A gdy by miał/a Pan/i podać jeden najważniejszy powód? --rot
01 Atrakcyjne ceny --hide:$P4B:{0} != "1"
02 Szybkość robienia zakupów
03 Łatwość robienia zakupów
04 Przejrzystość/ łatwość poruszania się
05 Estetyka/wygląd (kolory, czcionka, design)
06 Dostępność poszukiwanych produktów
07 Szeroki wybór produktów
08 Mam zaufanie do serwisu

ukrywanie elementów nie działa jak poprzednio, należy po spacji napisać --hide, wcześniej działało bez spacji.

**Comment by rkorzen** [comment]
Poprawione w Fix#2 i późniejszych pracach na master
Teraz nie powinno mieć znaczenia czy przed --hide będa jakieś spacje czy nie.
