### ISSUE TITLE
błąd w kafeterii

### ISSUE THREAD

**Issue by xmulara** [rkorzen/KreaturaParser#3]
Nie działa kafeteria jeśli występuje w niej znak : (dwukropek), taki element pomija

przykład: (drugi element zostaje pominięty i nie będzie go w kafeterii)
Q M P4B Dlaczego właśnie ten sklep internetowy Pan(i) wybrał(a)? --rot
01 Atrakcyjne ceny
02 Szybkość: robienia zakupów
03 Łatwość robienia zakupów

**Comment by rkorzen** [comment]
Poprawione
